name: Run TestNG Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Java distribution
          java-version: '17'       # Java version, change as needed

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
            path: ~/.m2
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn install -DskipTests

      - name: Run Selenium Tests
        env:
          SELENIUM_URL: http://localhost:4444/wd/hub  # URL to Selenium server
        run: mvn test -Dselenium.server.url=$SELENIUM_URL

      - name: Run TestNG Tests
        run: mvn test -DsuiteXmlFile=src/test/resources/testng.xml